# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np
np.set_printoptions(suppress=True)

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [3]:

print(f"Dimensions: {A.ndim}")
print(f"Shape: {A.shape}")
print(f"Size: {A.size}")
print(f"Type: {A.dtype}")

Dimensions: 2
Shape: (3, 5)
Size: 15
Type: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print(f"Elementwise subtraction B-C: \n{B-C}")
print(f"Elementwise multiplication B*C: \n{B*C}")
print(f"Matrix multiplication B@C: \n{B@C}")


Elementwise subtraction B-C: 
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication B*C: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication B@C: 
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(f"exp: \n{np.array_str(np.exp(B),precision=3)}")

exp: 
[[   2.718    7.389   20.086]
 [  54.598  148.413  403.429]
 [1096.633 2980.958 8103.084]]


In [8]:
print(B)
print(f"Min - flat: {B.min()}")
print(f"Min - Col:  {B.min(axis=0)}")
print(f"Min - Row:  {B.min(axis=1)}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Min - flat: 1
Min - Col:  [1 2 3]
Min - Row:  [1 4 7]


In [9]:
# B1=np.array([[7,-4,2],[4,5,6],[1,5,-5]])
B1=B
print(B1)
# print(f"Min - flat: {np.ravel(B1)[B1.argmin()]}")
print(f"Min index - flat: {B1.argmin()}")
# print(f"Min index - Col:  {B1.argmin(axis=0)}")
print(f"Min index - Row:  {B1.argmin(axis=1)}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Min index - flat: 0
Min index - Row:  [0 0 0]


In [10]:
print(f"Sum - flat: {B.sum()}")
print(f"Mean - Col:  {B1.mean(axis=0)}")
print(f"Median - Col:  {np.median(B1,axis=0)}")



Sum - flat: 45
Mean - Col:  [4. 5. 6.]
Median - Col:  [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [11]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [13]:
# It is the same as A[1,:] i.e if the second dimension/axis is omitted it takes the whole row vector 1. If you have A[,1] you will get the whole col vector for the second dimesion at col 1: [2,7,12]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [14]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [16]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [17]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [18]:
# a is a 1-dim vector with length 30, b is a reshaped copy with three dimensions - 2 arrays,three rows and the columns is set to -1 for numpy to calculate the dimension (in this case it should have been 5)  

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [19]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [20]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [21]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [22]:
def add_mult_matrices(A,B,op):
  if isinstance(A, np.ndarray) and isinstance(B, np.ndarray):
    A_dim=A.shape
    B_dim=B.shape
  else: 
    raise TypeError("Sorry, A and B input needs to be numpy array types")
  
  match op:
    case 'add':
      if A_dim != B_dim:
        raise Exception("Wrong dimensions, can't do addition")
      return A+B
    case 'multiply':
      if A_dim[1] != B_dim[0]:
        raise Exception("Wrong dimensions, can't do multiplication")
      return A@B
    case _:
      raise Exception("Sorry, you need to specify operation [add|multiply]")

X1=np.array([[1,2,3],[4,5,6]])
X2=np.array([[1,1,1],[2,2,2]])
X3=np.array([[1,2],[2,3],[3,4]])

print(f"X1[{X1.shape[0]}x{X1.shape[1]}]=\n{X1}")
print(f"X2[{X2.shape[0]}x{X2.shape[1]}]=\n{X2}")
print(f"X3[{X3.shape[0]}x{X3.shape[1]}]=\n{X3}")
print()
print(f"X1+X2=\n{add_mult_matrices(X1,X2,'add')}")
print()
print(f"X1@X3=\n{add_mult_matrices(X1,X3,'multiply')}")


X1[2x3]=
[[1 2 3]
 [4 5 6]]
X2[2x3]=
[[1 1 1]
 [2 2 2]]
X3[3x2]=
[[1 2]
 [2 3]
 [3 4]]

X1+X2=
[[2 3 4]
 [6 7 8]]

X1@X3=
[[14 20]
 [32 47]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [23]:
print("10.1.1:")
print("--------------")
x=np.array([[4,3]])
print(f"x = {x}")
print(f"\n(a) Dimension of x is {x.shape}")
print(f"\n(b)      5x = {5*x}")
print(f"\n(c)      3x = {3*x}")
print(f"\n(d)   5x+3x = {5*x+3*x}")
print(f"\n(e)      8x = {8*x}")
print(f"\n(f)    4x-x = {4*x-x}")
print(f"\n(g)     x.T =\n{x.T}\n      Dimension of x.T = {(x.T).shape}")
print(f"\n(h)   x+x.T = is undefined since they have different shape [1x2] vs. [2x1]")
print(f"\n(i)   ||x|| = {np.linalg.norm(x)} or using sqrt(x*x.T) = {np.sqrt(x@x.T)} ... [1x2][2x1]->[1x1]")


10.1.1:
--------------
x = [[4 3]]

(a) Dimension of x is (1, 2)

(b)      5x = [[20 15]]

(c)      3x = [[12  9]]

(d)   5x+3x = [[32 24]]

(e)      8x = [[32 24]]

(f)    4x-x = [[12  9]]

(g)     x.T =
[[4]
 [3]]
      Dimension of x.T = (2, 1)

(h)   x+x.T = is undefined since they have different shape [1x2] vs. [2x1]

(i)   ||x|| = 5.0 or using sqrt(x*x.T) = [[5.]] ... [1x2][2x1]->[1x1]


In [24]:
print("10.1.2:")
print("--------------")
v=np.array([[3,7,0,11]]).T
print(f"v =\n{v}")
print(f"\n(a) Dimension of v is {v.shape}")
print(f"\n(b)     2v =\n{2*v}")
print(f"\n(c)  5v+2v =\n{5*v+2*v}")
print(f"\n(d)  4v-2v =\n{4*v-2*v}")
print(f"\n(e)    v.T =\n{v.T}\n      Dimension of v.T = {(v.T).shape}")
print(f"\n(f)  ||v|| = {np.linalg.norm(v)} or using sqrt(v.T@v) = {np.sqrt(v.T@v)} ... [1x4][4x1]->[1x1]")


10.1.2:
--------------
v =
[[ 3]
 [ 7]
 [ 0]
 [11]]

(a) Dimension of v is (4, 1)

(b)     2v =
[[ 6]
 [14]
 [ 0]
 [22]]

(c)  5v+2v =
[[21]
 [49]
 [ 0]
 [77]]

(d)  4v-2v =
[[ 6]
 [14]
 [ 0]
 [22]]

(e)    v.T =
[[ 3  7  0 11]]
      Dimension of v.T = (1, 4)

(f)  ||v|| = 13.379088160259652 or using sqrt(v.T@v) = [[13.37908816]] ... [1x4][4x1]->[1x1]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [25]:
print("10.2.1:")
print("--------------")
A=np.array([[2,1,-1],[1,-1,1]])
B=np.array([[4,-2,1],[2,-4,-2]])
C=np.array([[1,2],[2,1]])
D=np.array([[3,4],[4,3]])
E=np.array([[1],[2]])
I=np.array([[1,0],[0,1]])


print(f"A =\n{A}")
print(f"B =\n{B}")
print(f"C =\n{C}")
print(f"D =\n{D}")
print(f"E =\n{E}")
print(f"I =\n{I}")


print(f"\n(a)        2A = \n{2*A}")
print(f"\n(b)      B-2A = \n{B-2*A}")
print(f"\n(c)     3C-2E = Not defined mathematically ... but with broadcasting (over cols) in Python: \n{3*C-2*E}")
print(f"\n(d)     2D-3C = \n{2*D-3*C}")
print(f"\n(e)    D.T+2D = \n{D.T+2*D}")
print(f"\n(f) 2C.T-2D.T = \n{2*C.T-2*D.T}")
print(f"\n(g)     A.T-B = Not defined mathematically  ... not possible to broadcast")
print(f"\n(h)       A*C = Not defined mathematically {A.shape} x {C.shape}")
print(f"\n(i)       C*D = {C.shape} x {D.shape}\n{C@D}")
print(f"\n(j)       C*B = {C.shape} x {B.shape}\n{C@B}")
print(f"\n(k)       C*I = {C.shape} x {I.shape}\n{C@I}")
print(f"\n(l)     A*B.T = {A.shape} x {B.T.shape}\n{A@B.T}")


10.2.1:
--------------
A =
[[ 2  1 -1]
 [ 1 -1  1]]
B =
[[ 4 -2  1]
 [ 2 -4 -2]]
C =
[[1 2]
 [2 1]]
D =
[[3 4]
 [4 3]]
E =
[[1]
 [2]]
I =
[[1 0]
 [0 1]]

(a)        2A = 
[[ 4  2 -2]
 [ 2 -2  2]]

(b)      B-2A = 
[[ 0 -4  3]
 [ 0 -2 -4]]

(c)     3C-2E = Not defined mathematically ... but with broadcasting (over cols) in Python: 
[[ 1  4]
 [ 2 -1]]

(d)     2D-3C = 
[[3 2]
 [2 3]]

(e)    D.T+2D = 
[[ 9 12]
 [12  9]]

(f) 2C.T-2D.T = 
[[-4 -4]
 [-4 -4]]

(g)     A.T-B = Not defined mathematically  ... not possible to broadcast

(h)       A*C = Not defined mathematically (2, 3) x (2, 2)

(i)       C*D = (2, 2) x (2, 2)
[[11 10]
 [10 11]]

(j)       C*B = (2, 2) x (2, 3)
[[  8 -10  -3]
 [ 10  -8   0]]

(k)       C*I = (2, 2) x (2, 2)
[[1 2]
 [2 1]]

(l)     A*B.T = (2, 3) x (3, 2)
[[5 2]
 [7 4]]


In [26]:
print("10.2.2:")
print("--------------")
A=np.array([[2,3,4],[5,4,1]])
print(f"A =\n{A}")
print(f"\n(j)     A*A.T = {A.shape} x {A.T.shape}\n{A@A.T}")


10.2.2:
--------------
A =
[[2 3 4]
 [5 4 1]]

(j)     A*A.T = (2, 3) x (3, 2)
[[29 26]
 [26 42]]


In [27]:
print("10.2.3:")
print("--------------")
A=np.array([[1,2],[2,4]])
B=np.array([[2,1],[1,3]])
C=np.array([[4,3],[0,2]])
print(f"A =\n{A}")
print(f"B =\n{B}")
print(f"C =\n{C}")

print(f"\n     A*B = {A.shape} x {B.shape}\n{A@B}")
print(f"\n     A*C = {A.shape} x {C.shape}\n{A@C}")
print(f"Is B == C ? Check using norm(B-C): {np.linalg.norm(B-C)} > 0, i.e B!=C")


10.2.3:
--------------
A =
[[1 2]
 [2 4]]
B =
[[2 1]
 [1 3]]
C =
[[4 3]
 [0 2]]

     A*B = (2, 2) x (2, 2)
[[ 4  7]
 [ 8 14]]

     A*C = (2, 2) x (2, 2)
[[ 4  7]
 [ 8 14]]
Is B == C ? Check using norm(B-C): 3.1622776601683795 > 0, i.e B!=C


In [28]:
print("10.2.4:(bonus)")
print("--------------")

print("Ax=b")

A=np.array([[3,2,4],[2,3,8],[4,1,3],[7,1,5]])
b=np.array([[7],[4],[11],[9]])
print(f"A = {A.shape}\n{A}")
print(f"b = {b.shape}\n{b}")


10.2.4:(bonus)
--------------
Ax=b
A = (4, 3)
[[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]]
b = (4, 1)
[[ 7]
 [ 4]
 [11]
 [ 9]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [29]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [30]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [31]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)


[  0   1   2 123]
[  2 123]
